### ISSUE TITLE
How to configure this task properly

### ISSUE THREAD

**Issue by nreddipalle** [OrbisInvestments/azure-pipelines-custom-tasks#15]
@ppejovic as mentioned as part of setup, I added this task as a pipeline decorator.. after first run.. I see this.. 
![image](https://user-images.githubusercontent.com/28302399/71267944-d00eb200-2319-11ea-9436-491b6f2e5d0a.png) and the current build source directory created a symbolic link with c:\vstsagent\A1\_work\g\1.

I expect the second run to actually create a new directory (9,10,5 etc) but use symbolic link path but its not doing it instead downloading the repo again completely.. 
![image](https://user-images.githubusercontent.com/28302399/71268091-195f0180-231a-11ea-8a91-35df03cbda38.png)

![image](https://user-images.githubusercontent.com/28302399/71268132-3398df80-231a-11ea-81bb-7c633d5d7501.png)
![image](https://user-images.githubusercontent.com/28302399/71268147-3e537480-231a-11ea-853f-9a9ad9fb4548.png)

Am I missing any configuration as part of checkout step.. Please suggest.. 
Thanks

**Comment by nreddipalle** [comment]
@ppejovic One more thing, I noticed is that.. as part of this sample pipeline.. it is setting the symbolic link at the end of run on folder 10.
![image](https://user-images.githubusercontent.com/28302399/71269477-74debe80-231d-11ea-8d15-1db7c1863e61.png)

![image](https://user-images.githubusercontent.com/28302399/71269498-7dcf9000-231d-11ea-9888-2b1b6578f69d.png)

![image](https://user-images.githubusercontent.com/28302399/71269513-8922bb80-231d-11ea-9561-701af8643f5f.png)

The subsequent run of the same pipeline on the same agent cleaning up the symbolic link and checking out the source again.. (I set clean to false as shown below).. am I missing anything?

![image](https://user-images.githubusercontent.com/28302399/71269629-c9823980-231d-11ea-8f3a-d6782eabcc2b.png)

![image](https://user-images.githubusercontent.com/28302399/71269658-dc950980-231d-11ea-8d97-04218a53c896.png)

#Run 16531 on Agent
![image](https://user-images.githubusercontent.com/28302399/71269775-1bc35a80-231e-11ea-81b0-53395810e797.png)

#Run 16532 on the same agent (checking out the complete repo again)
![image](https://user-images.githubusercontent.com/28302399/71270454-9b9df480-231f-11ea-8b01-32c834e0bdee.png)

Let me know if I miss anything as part of setup..

**Comment by ppejovic** [comment]
Hi @nreddipalle. If you have multiple work directories, i.e. _work\1, _work\5, etc that would suggest you are running multiple pipelines? Is that correct? The same pipeline should always reuse the same _work sub-directory.

**Comment by ppejovic** [comment]
Just adding more info. The task always runs at the end of the build, so on first run of a pipeline on a new/clean agent, the repo will initially be cloned to the pipeline's working directory then it will be deduped. However for the repo not be recloned each time, the pipeline has to reuse it's working directory (I can't think of a scenario where this isn't the case), and all pipelines that build the same repository should not **clean sources**. However, if the former is true and some pipelines do **clean sources** then it will only be the shared clone of the repository that gets recloned on subsequent runs. 

HTH

**Comment by ppejovic** [comment]
If you can add a few bits of info it will help me debug the issue. 

- Agent version are you using
- Account type the agent is running under and whether it is a local admin on the agent server
- Run the pipeline to create the working directory and symlink. Then on the next run, run the pipeline with diagnostics. If you can please provide the logs from the checkout step.

Thanks

**Comment by nreddipalle** [comment]
@ppejovic for this screenshot..https://github.com/OrbisInvestments/azure-pipelines-custom-tasks/issues/15#issue-541074481 yes I am running multiple pipelines against the same agent.. (unless my understanding is wrong, I thought this task still works and checks if there is a symlink exists already and doesn't checkout if one exists already (which ever is the current folder is 1,2,3,4,5,6,7,8). 

I am running on Agent Version  2.163.1
Yes the account agent is running is a local admin account

As far testing, I ran the pipeline and it picks C:/vstsagent/A1/_work/6/s/.git/ as the working folder, so it checked out and performed symlink at the end as shown below. 
![image](https://user-images.githubusercontent.com/28302399/71285977-7667b100-2334-11ea-975b-254856cfa24b.png)

![image](https://user-images.githubusercontent.com/28302399/71285996-82537300-2334-11ea-845f-eb2948aee25d.png)

Subsequent run of the same pipeline against the same working directory performing complete checkout again.. 

![image](https://user-images.githubusercontent.com/28302399/71286080-baf34c80-2334-11ea-8844-eb874475c1b6.png)

![image](https://user-images.githubusercontent.com/28302399/71286097-c9416880-2334-11ea-937b-5c2c17d68fc2.png)

![image](https://user-images.githubusercontent.com/28302399/71286126-d8c0b180-2334-11ea-82a5-17f9acb69d7d.png)

Checkout Task Log.. 
[4.txt](https://github.com/OrbisInvestments/azure-pipelines-custom-tasks/files/3989929/4.txt)

**Comment by nreddipalle** [comment]
Hello @ppejovic any update regarding this on where I am doing wrong?

**Comment by orbis-richcumbers** [comment]
Hi @nreddipalle. Pero is currently on vacation, taking a well earned break. He will be back on the 6th January. Sorry for the delay!

**Comment by orbis-richcumbers** [comment]
Oops. I did not mean to close this thread...

**Comment by nreddipalle** [comment]
@ppejovic ??

**Comment by ppejovic** [comment]
I’ll have to test the task against the agent version you’re using. I’ll be able to do this next week.

**Comment by nreddipalle** [comment]
@ppejovic any update on this?

**Comment by ppejovic** [comment]
@nreddipalle I tested with agent version 2.163.1 and I can't recreate the issue, the task is compatible with that version. 

Are your build agents provisioned on the fly? Is the working directory getting remounted between each run of the pipeline? If the symlink is present at the end of the first run, but not present at the beginning of the second I can't think what else would be responsible for it being removed.

**Comment by ppejovic** [comment]
@nreddipalle Any update? I'll close this off if there's nothing to add. Cheers

**Comment by nreddipalle** [comment]
I will check on Monday and update.

**Comment by ppejovic** [comment]
Please let us know if you want us to reopen.
