### ISSUE TITLE
Instead of symlink, could this use a worktree feature to create multiple working folders?

### ISSUE THREAD

**Issue by jessehouwing** [OrbisInvestments/azure-pipelines-custom-tasks#17]
```
git worktree
```

Will allow multiple working folders for a single `.git` folder. Each folder can checkout whichever branch or commit they want.

This would allow the task to not rely on admin permissions.

See also: https://git-scm.com/docs/git-worktree

**Comment by ppejovic** [comment]
Thanks for the contribution @jessehouwing. I'd like to see the admin requirement removed. I just need to get my head around how we'd leverage `git worktree`, it looks like a more elegant solution. 

My understanding is that the task would create a working tree from the shared clone to the `Build.SourcesDirectory` path for the pipeline. 

Is it the case that the `git` operations then performed by the pipelines agent on the sources directory will just work like it was operating on the main working tree of its own clone? If that's the case then great. I will test this when I get an opportunity. 

There is the overhead of having a working tree for each pipeline the agent runs but I think that's fine, the problem we're trying to solve is not having `n` repository clones for `n` pipelines.

**Comment by jessehouwing** [comment]
That's the idea.

**Comment by ppejovic** [comment]
It doesn't look like this is going to work @jessehouwing. In the checkout phase of a pipeline the agent does some validation on the repo in the source directory to ensure the origin url matches what is expected. Part of that [includes a check](https://github.com/microsoft/azure-pipelines-agent/blob/344295832dcfca41a76abaae37cabb4b54b92e92/src/Agent.Plugins/GitSourceProvider.cs#L1241) for the presence of a `.git` directory. In the case of a linked working tree created by `git worktree`, the `.git` is actually a file with a pointer to the `.git` directory in the main working tree:

> Within a linked working tree, $GIT_DIR is set to point to this private directory (e.g. /path/main/.git/worktrees/test-next in the example) and $GIT_COMMON_DIR is set to point back to the main working tree’s $GIT_DIR (e.g. /path/main/.git). These settings are made in a .git file located at the top directory of the linked working tree.

That results in the agent trashing the source directory and cloning fresh. It would be nice if that repository check used something like `git rev-parse --is-inside-work-tree` as a more robust way to determine if it was working on a valid git repo. 

Finally, there are some [bugs](https://git-scm.com/docs/git-worktree#_bugs) in `git worktree` that lead me to believe this may not act consistently in some scenarios. 

I'm going to revisit the symlink approach as it may be possible to achieve this with `junctions` which I believe don't have an admin requirement. I'll close this issue but if you have any further ideas I'd be happy to hear them.
